services:
  backend:
    build:
      context: ./Back-end
    ports:
      - "5000:8080"
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=${DB_CONNECTION_STRING}
  
  frontend:
    build:
      context: ./Front-end
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http:localhost:5000
    depends_on:
      - backend